langs:
  - langcode: en
    lang_string: English
  - langcode: de
    lang_string: Deutsch
  - langcode: es
    lang_string: Español
  - langcode: fr-fr
    lang_string: Française
  - langcode: zh-cn
    lang_string: 简体中文
  - langcode: zh-tw
    lang_string: 繁體中文
