langs:
  - langcode: en
    lang_string: English
  - langcode: es
    lang_string: Español
  - langcode: fr
    lang_string: Français
  - langcode: zh-CN
    lang_string: 简体中文
  - langcode: zh-TW
    lang_string: 繁體中文
