langs:
  - langcode: en
    lang_string: English
  - langcode: de
    lang_string: Deutsch
  - langcode: es
    lang_string: Español
  - langcode: fr
    lang_string: Français
  - langcode: zh-CN
    lang_string: 简体中文
  - langcode: zh-TW
    lang_string: 繁體中文
  - langcode: ja
    lang_string: 日本語
  - langcode: ko
    lang_string: 한국어
  - langcode: pt-BR
    lang_string: Português Brasileiro
  - langcode: ru
    lang_string: Русский
